
name: pygbag_build
on: [workflow_dispatch]
permissions:
  contents: write

jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
            ref: ${{ github.ref }}
    - name: Checkout
      run: |
            python -m pip install pygbag
            python -m pygbag --ume_block 0 --template utils/default.tmpl --icon project/assets/icon.png --no_opt --build $GITHUB_WORKSPACE/project/main.py
    - name: Run find-and-replace to remove refs/heads/
      uses: mad9000/actions-find-and-replace-string@5
      id: findandreplace
      with:
        source: "${{ github.ref }}"
        find: "refs/heads/"
        replace: ""
    - name: Checkout
      run: echo "${{ github.ref }} _ ${{ steps.findandreplace.outputs.result }}"
    - name: "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: project/build/web
        target-folder: ${{ github.event.repository.name }}/${{ steps.findandreplace.outputs.result }} 
