
name: pygbag_build
on: [workflow_dispatch]
permissions:
  contents: write

jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
            ref: ${{ github.ref }}
    - name: Checkout
      run: |
            python -m pip install pygbag
            python -m pygbag --ume_block 0 --template utils/black.tmpl --icon project/assets/icon.png --no_opt --build $GITHUB_WORKSPACE/project/main.py            
    - name: replace str
      id: replace_str
      run: echo BRANCH=${GITHUB_REF//refs\/heads\//}  >> $GITHUB_OUTPUT
    - name: "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: project/build/web
        target-folder: ${{ steps.replace_str.outputs.BRANCH }}
